version: "3"
services:
  redis:
    image: redis:3.0-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    ports:
      - 127.0.0.1:6379:6379
  fluentd:
    image: fluent/fluentd:v1.2
    ports:
      - 127.0.0.1:24224:24224
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
    environment:
      - FLUENTD_CONF=fluentd.conf
